### ISSUE TITLE
AttributeError: vocab attribute removed from Keyed Vector in Gensim 4.0.0

### ISSUE THREAD

**Issue by mcgeestephen** [GeneDx/txt2hpo#41]
Odd AttributeError with the following query:
```
from txt2hpo.extract import Extractor
extract=Extractor()
extract.hpo('blood group').hpids
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/stephen/anaconda3/lib/python3.8/site-packages/txt2hpo-0.2.2-py3.8.egg/txt2hpo/extract.py", line 236, in hpo
    extracted_terms.resolve_conflicts()
  File "/home/stephen/anaconda3/lib/python3.8/site-packages/txt2hpo-0.2.2-py3.8.egg/txt2hpo/extract.py", line 98, in resolve_conflicts
    similarity_scores.append(similarity_term_to_context(term, entry['context'], self.model))
  File "/home/stephen/anaconda3/lib/python3.8/site-packages/txt2hpo-0.2.2-py3.8.egg/txt2hpo/nlp.py", line 79, in similarity_term_to_context
    term_tokens = remove_out_of_vocab(remove_stopwords(hpo_term_definition).split())
  File "/home/stephen/anaconda3/lib/python3.8/site-packages/txt2hpo-0.2.2-py3.8.egg/txt2hpo/nlp.py", line 75, in remove_out_of_vocab
    return [x for x in tokens if x in model.vocab]
  File "/home/stephen/anaconda3/lib/python3.8/site-packages/txt2hpo-0.2.2-py3.8.egg/txt2hpo/nlp.py", line 75, in <listcomp>
    return [x for x in tokens if x in model.vocab]
  File "/home/stephen/anaconda3/lib/python3.8/site-packages/gensim-4.0.0b0-py3.8-linux-x86_64.egg/gensim/models/keyedvectors.py", line 648, in vocab
    raise AttributeError(
AttributeError: The vocab attribute was removed from KeyedVector in Gensim 4.0.0.
Use KeyedVector's .key_to_index dict, .index_to_key list, and methods .get_vecattr(key, attr) and .set_vecattr(key, attr, new_val) instead.
See https://github.com/RaRe-Technologies/gensim/wiki/Migrating-from-Gensim-3.x-to-4

**Comment by vgainullin** [comment]
Thanks, will need to modify to update the code to play by gensim v4.0 rules.

**Comment by vgainullin** [comment]
Here is a link to directions on how to port this exact attribute name: https://github.com/RaRe-Technologies/gensim/wiki/Migrating-from-Gensim-3.x-to-4#4-vocab-dict-became-key_to_index-for-looking-up-a-keys-integer-index-or-get_vecattr-and-set_vecattr-for-other-per-key-attributes
