### ISSUE TITLE
Installation deprecated

### ISSUE THREAD

**Issue by poutant1** [GeneDx/txt2hpo#59]
I'm having issues with installing the package. Trying to install the package using setup.py,  I get

`Processing dependencies for txt2hpo==2021.0
Searching for gensim==3.8.1
Reading https://pypi.org/simple/gensim/
Download error on https://pypi.org/simple/gensim/: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997) -- Some packages may not be found!
Couldn't find index page for 'gensim' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.org/simple/
Download error on https://pypi.org/simple/: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997) -- Some packages may not be found!
No local packages or working download links found for gensim==3.8.1
error: Could not find suitable distribution for Requirement.parse('gensim==3.8.1')`

Is this a problem with gensim or txt2hpo?

installation through pip gives

`Installing build dependencies ... error
  error: subprocess-exited-with-error
  
  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [212 lines of output]
      Collecting setuptools
        Using cached setuptools-62.3.2-py3-none-any.whl (1.2 MB)
      Collecting wheel
        Using cached wheel-0.37.1-py2.py3-none-any.whl (35 kB)
      Collecting cython>=0.25
        Using cached Cython-0.29.30-py2.py3-none-any.whl (985 kB)
      Collecting cymem<2.1.0,>=2.0.2
        Using cached cymem-2.0.6-cp310-cp310-macosx_11_0_arm64.whl (30 kB)
      Collecting preshed<3.1.0,>=3.0.2
        Using cached preshed-3.0.6-cp310-cp310-macosx_11_0_arm64.whl (101 kB)
      Collecting murmurhash<1.1.0,>=0.28.0
        Using cached murmurhash-1.0.7-cp310-cp310-macosx_11_0_arm64.whl (19 kB)
      Collecting thinc==7.4.0
        Using cached thinc-7.4.0.tar.gz (1.3 MB)
        Preparing metadata (setup.py): started
        Preparing metadata (setup.py): finished with status 'done'
      Collecting blis<0.5.0,>=0.4.0
        Using cached blis-0.4.1.tar.gz (1.8 MB)
        Preparing metadata (setup.py): started
        Preparing metadata (setup.py): finished with status 'done'
      Collecting wasabi<1.1.0,>=0.0.9
        Using cached wasabi-0.9.1-py3-none-any.whl (26 kB)
      Collecting srsly<1.1.0,>=0.0.6
        Using cached srsly-1.0.5-cp310-cp310-macosx_10_9_universal2.whl
      Collecting catalogue<1.1.0,>=0.0.7
        Using cached catalogue-1.0.0-py2.py3-none-any.whl (7.7 kB)
      Collecting numpy>=1.7.0
        Using cached numpy-1.22.4-cp310-cp310-macosx_11_0_arm64.whl (12.8 MB)
      Collecting plac<1.2.0,>=0.9.6
        Using cached plac-1.1.3-py2.py3-none-any.whl (20 kB)
      Collecting tqdm<5.0.0,>=4.10.0
        Using cached tqdm-4.64.0-py2.py3-none-any.whl (78 kB)
      Building wheels for collected packages: thinc, blis
        Building wheel for thinc (setup.py): started
        Building wheel for thinc (setup.py): finished with status 'error'
        error: subprocess-exited-with-error
      
        × python setup.py bdist_wheel did not run successfully.
        │ exit code: 1
        ╰─> [32 lines of output]
            /Users/tuomas.poutanen/koodi/txt2hpo/venv/lib/python3.10/site-packages/setuptools/installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
              warnings.warn(
            Traceback (most recent call last):
              File "<string>", line 2, in <module>
              File "<pip-setuptools-caller>", line 34, in <module>
              File "/private/var/folders/wp/j33q8lm90yx5crb6z4192vbw0000gn/T/pip-install-t6ymh64w/thinc_94f9b50ea8df4fe28f30b0ef670e6c3e/setup.py", line 264, in <module>
                setup_package()
              File "/private/var/folders/wp/j33q8lm90yx5crb6z4192vbw0000gn/T/pip-install-t6ymh64w/thinc_94f9b50ea8df4fe28f30b0ef670e6c3e/setup.py", line 201, in setup_package
                setup(
              File "/Users/tuomas.poutanen/koodi/txt2hpo/venv/lib/python3.10/site-packages/setuptools/__init__.py", line 86, in setup
                _install_setup_requires(attrs)
              File "/Users/tuomas.poutanen/koodi/txt2hpo/venv/lib/python3.10/site-packages/setuptools/__init__.py", line 80, in _install_setup_requires
                dist.fetch_build_eggs(dist.setup_requires)
              File "/Users/tuomas.poutanen/koodi/txt2hpo/venv/lib/python3.10/site-packages/setuptools/dist.py", line 861, in fetch_build_eggs
                resolved_dists = pkg_resources.working_set.resolve(
              File "/Users/tuomas.poutanen/koodi/txt2hpo/venv/lib/python3.10/site-packages/pkg_resources/__init__.py", line 789, in resolve
                dist = best[req.key] = env.best_match(
              File "/Users/tuomas.poutanen/koodi/txt2hpo/venv/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1075, in best_match
                return self.obtain(req, installer)
              File "/Users/tuomas.poutanen/koodi/txt2hpo/venv/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1087, in obtain
                return installer(requirement)
              File "/Users/tuomas.poutanen/koodi/txt2hpo/venv/lib/python3.10/site-packages/setuptools/dist.py", line 941, in fetch_build_egg
                return fetch_build_egg(self, req)
              File "/Users/tuomas.poutanen/koodi/txt2hpo/venv/lib/python3.10/site-packages/setuptools/installer.py", line 87, in fetch_build_egg
                wheel.install_as_egg(dist_location)
              File "/Users/tuomas.poutanen/koodi/txt2hpo/venv/lib/python3.10/site-packages/setuptools/wheel.py", line 96, in install_as_egg
                self._install_as_egg(destination_eggdir, zf)
              File "/Users/tuomas.poutanen/koodi/txt2hpo/venv/lib/python3.10/site-packages/setuptools/wheel.py", line 104, in _install_as_egg
                self._convert_metadata(zf, destination_eggdir, dist_info, egg_info)
              File "/Users/tuomas.poutanen/koodi/txt2hpo/venv/lib/python3.10/site-packages/setuptools/wheel.py", line 148, in _convert_metadata
                os.rename(dist_info, egg_info)
            OSError: [Errno 66] Directory not empty: '/private/var/folders/wp/j33q8lm90yx5crb6z4192vbw0000gn/T/pip-install-t6ymh64w/thinc_94f9b50ea8df4fe28f30b0ef670e6c3e/.eggs/numpy-1.22.4-py3.10-macosx-10.9-universal2.egg/numpy-1.22.4.dist-info' -> '/private/var/folders/wp/j33q8lm90yx5crb6z4192vbw0000gn/T/pip-install-t6ymh64w/thinc_94f9b50ea8df4fe28f30b0ef670e6c3e/.eggs/numpy-1.22.4-py3.10-macosx-10.9-universal2.egg/EGG-INFO'
            [end of output]
      
        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for thinc
        Running setup.py clean for thinc
        Building wheel for blis (setup.py): started
        Building wheel for blis (setup.py): finished with status 'error'
        error: subprocess-exited-with-error
      
        × python setup.py bdist_wheel did not run successfully.
        │ exit code: 1
        ╰─> [31 lines of output]
            BLIS_COMPILER? None
            /Users/tuomas.poutanen/koodi/txt2hpo/venv/lib/python3.10/site-packages/setuptools/installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
              warnings.warn(
            Traceback (most recent call last):
              File "<string>", line 2, in <module>
              File "<pip-setuptools-caller>", line 34, in <module>
              File "/private/var/folders/wp/j33q8lm90yx5crb6z4192vbw0000gn/T/pip-install-t6ymh64w/blis_2c4c791d2a814128855adaa7496d734e/setup.py", line 239, in <module>
                setup(
              File "/Users/tuomas.poutanen/koodi/txt2hpo/venv/lib/python3.10/site-packages/setuptools/__init__.py", line 86, in setup
                _install_setup_requires(attrs)
              File "/Users/tuomas.poutanen/koodi/txt2hpo/venv/lib/python3.10/site-packages/setuptools/__init__.py", line 80, in _install_setup_requires
                dist.fetch_build_eggs(dist.setup_requires)
              File "/Users/tuomas.poutanen/koodi/txt2hpo/venv/lib/python3.10/site-packages/setuptools/dist.py", line 861, in fetch_build_eggs
                resolved_dists = pkg_resources.working_set.resolve(
              File "/Users/tuomas.poutanen/koodi/txt2hpo/venv/lib/python3.10/site-packages/pkg_resources/__init__.py", line 789, in resolve
                dist = best[req.key] = env.best_match(
              File "/Users/tuomas.poutanen/koodi/txt2hpo/venv/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1075, in best_match
                return self.obtain(req, installer)
              File "/Users/tuomas.poutanen/koodi/txt2hpo/venv/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1087, in obtain
                return installer(requirement)
              File "/Users/tuomas.poutanen/koodi/txt2hpo/venv/lib/python3.10/site-packages/setuptools/dist.py", line 941, in fetch_build_egg
                return fetch_build_egg(self, req)
              File "/Users/tuomas.poutanen/koodi/txt2hpo/venv/lib/python3.10/site-packages/setuptools/installer.py", line 87, in fetch_build_egg
                wheel.install_as_egg(dist_location)
              File "/Users/tuomas.poutanen/koodi/txt2hpo/venv/lib/python3.10/site-packages/setuptools/wheel.py", line 96, in install_as_egg
                self._install_as_egg(destination_eggdir, zf)
              File "/Users/tuomas.poutanen/koodi/txt2hpo/venv/lib/python3.10/site-packages/setuptools/wheel.py", line 104, in _install_as_egg
                self._convert_metadata(zf, destination_eggdir, dist_info, egg_info)
              File "/Users/tuomas.poutanen/koodi/txt2hpo/venv/lib/python3.10/site-packages/setuptools/wheel.py", line 148, in _convert_metadata
                os.rename(dist_info, egg_info)
            OSError: [Errno 66] Directory not empty: '/private/var/folders/wp/j33q8lm90yx5crb6z4192vbw0000gn/T/pip-install-t6ymh64w/blis_2c4c791d2a814128855adaa7496d734e/.eggs/numpy-1.22.4-py3.10-macosx-10.9-universal2.egg/numpy-1.22.4.dist-info' -> '/private/var/folders/wp/j33q8lm90yx5crb6z4192vbw0000gn/T/pip-install-t6ymh64w/blis_2c4c791d2a814128855adaa7496d734e/.eggs/numpy-1.22.4-py3.10-macosx-10.9-universal2.egg/EGG-INFO'
            [end of output]
      
        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for blis
        Running setup.py clean for blis
        error: subprocess-exited-with-error
      
        × python setup.py clean did not run successfully.
        │ exit code: 1
        ╰─> [31 lines of output]
            BLIS_COMPILER? None
            /Users/tuomas.poutanen/koodi/txt2hpo/venv/lib/python3.10/site-packages/setuptools/installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
              warnings.warn(
            Traceback (most recent call last):
              File "<string>", line 2, in <module>
              File "<pip-setuptools-caller>", line 34, in <module>
              File "/private/var/folders/wp/j33q8lm90yx5crb6z4192vbw0000gn/T/pip-install-t6ymh64w/blis_2c4c791d2a814128855adaa7496d734e/setup.py", line 239, in <module>
                setup(
              File "/Users/tuomas.poutanen/koodi/txt2hpo/venv/lib/python3.10/site-packages/setuptools/__init__.py", line 86, in setup
                _install_setup_requires(attrs)
              File "/Users/tuomas.poutanen/koodi/txt2hpo/venv/lib/python3.10/site-packages/setuptools/__init__.py", line 80, in _install_setup_requires
                dist.fetch_build_eggs(dist.setup_requires)
              File "/Users/tuomas.poutanen/koodi/txt2hpo/venv/lib/python3.10/site-packages/setuptools/dist.py", line 861, in fetch_build_eggs
                resolved_dists = pkg_resources.working_set.resolve(
              File "/Users/tuomas.poutanen/koodi/txt2hpo/venv/lib/python3.10/site-packages/pkg_resources/__init__.py", line 789, in resolve
                dist = best[req.key] = env.best_match(
              File "/Users/tuomas.poutanen/koodi/txt2hpo/venv/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1075, in best_match
                return self.obtain(req, installer)
              File "/Users/tuomas.poutanen/koodi/txt2hpo/venv/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1087, in obtain
                return installer(requirement)
              File "/Users/tuomas.poutanen/koodi/txt2hpo/venv/lib/python3.10/site-packages/setuptools/dist.py", line 941, in fetch_build_egg
                return fetch_build_egg(self, req)
              File "/Users/tuomas.poutanen/koodi/txt2hpo/venv/lib/python3.10/site-packages/setuptools/installer.py", line 87, in fetch_build_egg
                wheel.install_as_egg(dist_location)
              File "/Users/tuomas.poutanen/koodi/txt2hpo/venv/lib/python3.10/site-packages/setuptools/wheel.py", line 96, in install_as_egg
                self._install_as_egg(destination_eggdir, zf)
              File "/Users/tuomas.poutanen/koodi/txt2hpo/venv/lib/python3.10/site-packages/setuptools/wheel.py", line 104, in _install_as_egg
                self._convert_metadata(zf, destination_eggdir, dist_info, egg_info)
              File "/Users/tuomas.poutanen/koodi/txt2hpo/venv/lib/python3.10/site-packages/setuptools/wheel.py", line 148, in _convert_metadata
                os.rename(dist_info, egg_info)
            OSError: [Errno 66] Directory not empty: '/private/var/folders/wp/j33q8lm90yx5crb6z4192vbw0000gn/T/pip-install-t6ymh64w/blis_2c4c791d2a814128855adaa7496d734e/.eggs/numpy-1.22.4-py3.10-macosx-10.9-universal2.egg/numpy-1.22.4.dist-info' -> '/private/var/folders/wp/j33q8lm90yx5crb6z4192vbw0000gn/T/pip-install-t6ymh64w/blis_2c4c791d2a814128855adaa7496d734e/.eggs/numpy-1.22.4-py3.10-macosx-10.9-universal2.egg/EGG-INFO'
            [end of output]
      
        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed cleaning build dir for blis
      Failed to build thinc blis
      Installing collected packages: wasabi, srsly, plac, murmurhash, cymem, wheel, tqdm, setuptools, preshed, numpy, cython, catalogue, blis, thinc
        Running setup.py install for blis: started
        Running setup.py install for blis: finished with status 'error'
        error: subprocess-exited-with-error
      
        × Running setup.py install for blis did not run successfully.
        │ exit code: 1
        ╰─> [31 lines of output]
            BLIS_COMPILER? None
            /Users/tuomas.poutanen/koodi/txt2hpo/venv/lib/python3.10/site-packages/setuptools/installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
              warnings.warn(
            Traceback (most recent call last):
              File "<string>", line 2, in <module>
              File "<pip-setuptools-caller>", line 34, in <module>
              File "/private/var/folders/wp/j33q8lm90yx5crb6z4192vbw0000gn/T/pip-install-t6ymh64w/blis_2c4c791d2a814128855adaa7496d734e/setup.py", line 239, in <module>
                setup(
              File "/Users/tuomas.poutanen/koodi/txt2hpo/venv/lib/python3.10/site-packages/setuptools/__init__.py", line 86, in setup
                _install_setup_requires(attrs)
              File "/Users/tuomas.poutanen/koodi/txt2hpo/venv/lib/python3.10/site-packages/setuptools/__init__.py", line 80, in _install_setup_requires
                dist.fetch_build_eggs(dist.setup_requires)
              File "/Users/tuomas.poutanen/koodi/txt2hpo/venv/lib/python3.10/site-packages/setuptools/dist.py", line 861, in fetch_build_eggs
                resolved_dists = pkg_resources.working_set.resolve(
              File "/Users/tuomas.poutanen/koodi/txt2hpo/venv/lib/python3.10/site-packages/pkg_resources/__init__.py", line 789, in resolve
                dist = best[req.key] = env.best_match(
              File "/Users/tuomas.poutanen/koodi/txt2hpo/venv/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1075, in best_match
                return self.obtain(req, installer)
              File "/Users/tuomas.poutanen/koodi/txt2hpo/venv/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1087, in obtain
                return installer(requirement)
              File "/Users/tuomas.poutanen/koodi/txt2hpo/venv/lib/python3.10/site-packages/setuptools/dist.py", line 941, in fetch_build_egg
                return fetch_build_egg(self, req)
              File "/Users/tuomas.poutanen/koodi/txt2hpo/venv/lib/python3.10/site-packages/setuptools/installer.py", line 87, in fetch_build_egg
                wheel.install_as_egg(dist_location)
              File "/Users/tuomas.poutanen/koodi/txt2hpo/venv/lib/python3.10/site-packages/setuptools/wheel.py", line 96, in install_as_egg
                self._install_as_egg(destination_eggdir, zf)
              File "/Users/tuomas.poutanen/koodi/txt2hpo/venv/lib/python3.10/site-packages/setuptools/wheel.py", line 104, in _install_as_egg
                self._convert_metadata(zf, destination_eggdir, dist_info, egg_info)
              File "/Users/tuomas.poutanen/koodi/txt2hpo/venv/lib/python3.10/site-packages/setuptools/wheel.py", line 148, in _convert_metadata
                os.rename(dist_info, egg_info)
            OSError: [Errno 66] Directory not empty: '/private/var/folders/wp/j33q8lm90yx5crb6z4192vbw0000gn/T/pip-install-t6ymh64w/blis_2c4c791d2a814128855adaa7496d734e/.eggs/numpy-1.22.4-py3.10-macosx-10.9-universal2.egg/numpy-1.22.4.dist-info' -> '/private/var/folders/wp/j33q8lm90yx5crb6z4192vbw0000gn/T/pip-install-t6ymh64w/blis_2c4c791d2a814128855adaa7496d734e/.eggs/numpy-1.22.4-py3.10-macosx-10.9-universal2.egg/EGG-INFO'
            [end of output]
      
        note: This error originates from a subprocess, and is likely not a problem with pip.
      error: legacy-install-failure
      
      × Encountered error while trying to install package.
      ╰─> blis
      
      note: This is an issue with the package mentioned above, not pip.
      hint: See above for output from the failure.
      WARNING: You are using pip version 22.0.4; however, version 22.1.2 is available.
      You should consider upgrading via the '/Users/tuomas.poutanen/koodi/txt2hpo/venv/bin/python -m pip install --upgrade pip' command.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.`

**Comment by jwhite3** [comment]
@poutant1 What version of python are you using when attempting the install?

**Comment by poutant1** [comment]
I'm currently using python 3.10.4

**Comment by jwhite3** [comment]
Got it. 

Would you mind trying an install with python 3.9?

**Comment by poutant1** [comment]
Tried installation using both 3.9.9. and 3.9.4 but both fail on something that seems to be related to spacy installation.

`Writing /var/folders/wp/j33q8lm90yx5crb6z4192vbw0000gn/T/easy_install-lomoy9z9/spacy-2.2.4/setup.cfg
Running spacy-2.2.4/setup.py -q bdist_egg --dist-dir /var/folders/wp/j33q8lm90yx5crb6z4192vbw0000gn/T/easy_install-lomoy9z9/spacy-2.2.4/egg-dist-tmp-sudu5iwl
WARNING: The wheel package is not available.
  ERROR: Command errored out with exit status 1:
   command: /Users/tuomas.poutanen/.pyenv/versions/3.9.4/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/wp/j33q8lm90yx5crb6z4192vbw0000gn/T/pip-wheel-ehz69_9m/thinc/setup.py'"'"'; __file__='"'"'/private/var/folders/wp/j33q8lm90yx5crb6z4192vbw0000gn/T/pip-wheel-ehz69_9m/thinc/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/wp/j33q8lm90yx5crb6z4192vbw0000gn/T/pip-wheel-fjwc6fho
       cwd: /private/var/folders/wp/j33q8lm90yx5crb6z4192vbw0000gn/T/pip-wheel-ehz69_9m/thinc/
  Complete output (7 lines):
  WARNING: The wheel package is not available.
  usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: setup.py --help [cmd1 cmd2 ...]
     or: setup.py --help-commands
     or: setup.py cmd --help
  
  error: invalid command 'bdist_wheel'
  ----------------------------------------
  ERROR: Failed building wheel for thinc
ERROR: Failed to build one or more wheels
error: Command '['/Users/tuomas.poutanen/.pyenv/versions/3.9.4/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/var/folders/wp/j33q8lm90yx5crb6z4192vbw0000gn/T/easy_install-lomoy9z9/spacy-2.2.4/temp/tmpg6etocs1', '--quiet', 'thinc==7.4.0']' returned non-zero exit status 1.`

**Comment by jwhite3** [comment]
Got it thanks. Would you mind trying 3.9.2? I was able to successfully install with 3.9.2. 

If that doesn't work for you, I'll do some more digging on this dependency issue.

**Comment by jwhite3** [comment]
@poutant1 I'm sorry to hear that. We will continue to investigate
