### ISSUE TITLE
TypeError: expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by ZQhaha** [GeneDx/txt2hpo#61]
**I have some issues about the example code. When I run the code below, it will report TypeError. Could you help me?**

- code:

```python
from txt2hpo.extract import Extractor
extract = Extractor()
result = extract.hpo("patient with developmental delay and hypotonia")
print(result.hpids)
````

- results

```python
Traceback (most recent call last):
  File "D:/PPD/2hpo.py", line 2, in <module>
    from txt2hpo.extract import Extractor
  File "D:\ProgramData\Anaconda3\envs\python36\lib\site-packages\txt2hpo\extract.py", line 7, in <module>
    from txt2hpo.build_tree import update_progress, hpo_network
  File "D:\ProgramData\Anaconda3\envs\python36\lib\site-packages\txt2hpo\build_tree.py", line 4, in <module>
    from txt2hpo.config import logger, config
  File "D:\ProgramData\Anaconda3\envs\python36\lib\site-packages\txt2hpo\config.py", line 29, in <module>
    config_directory = os.path.join(os.environ.get('HOME'), f'.{__project__}')
  File "D:\ProgramData\Anaconda3\envs\python36\lib\ntpath.py", line 76, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType
````

**Comment by krttrr** [comment]
I was able to reproduce this issue which is specific to Windows.

@rebeccaito can you update the use of os.environ.get('HOME') in config.py? Turns out that is not cross-platform for Windows. Here's a Stackoverflow with some alternatives: https://stackoverflow.com/questions/4028904/what-is-a-cross-platform-way-to-get-the-home-directory
